### ISSUE TITLE
Javacript highlight colors not being displayed correctly

### ISSUE THREAD

**Issue by TerrenceLJones** [atom/language-javascript#308]
I am experiencing an issue with the syntax highlight of my Javascript files. Here a before and after screen shot (the first screenshot is from a couple weeks ago...the second is from today). I have not knowingly changed anything. Does anyone know how this could have happened and how I could fix it?

<img width="969" alt="screen shot 2016-01-13 at 9 38 40 pm" src="https://cloud.githubusercontent.com/assets/7111256/12429053/cb0c6ce0-bead-11e5-9351-fe3b901188b5.png">
![screen shot 2016-01-19 at 1 07 42 pm](https://cloud.githubusercontent.com/assets/7111256/12429059/d2701dec-bead-11e5-9aa7-cda8fd9b8eae.png)

**Comment by 50Wliu** [comment]
Your Atom most likely updated to 1.4.0 which contains many language-javascript improvements.  You can "fix" it by following the steps here: https://github.com/atom/one-dark-syntax/issues/60#issuecomment-172628426 (provided you're using a syntax theme that follows conventions).

See also #263, #258, and atom/atom#9562.

**Comment by TerrenceLJones** [comment]
@50Wliu Sorry I didn't know of any other way to describe what I meant. The `EditTask.DurationDroplistComponent` for my Marionette view has always had a white color...now it has a green color...So to me it is not displaying correctly (or as it has normally been displayed).

**Comment by 50Wliu** [comment]
Yep, before that didn't have any specific scopes associated with it.  Now it does, and your syntax theme picked up on that and decided to color it green.

**Comment by TerrenceLJones** [comment]
@50Wliu Will the suggested fix in https://github.com/atom/one-dark-syntax/issues/60#issuecomment-172628426 work for seti-syntax?

**Comment by TerrenceLJones** [comment]
Whelp this fix was the only thing that would override my colors:

```css

atom-text-editor::shadow span.meta.method-call.js > span.variable.other.object.js {
color: #d4d7d6;
}
atom-text-editor::shadow span.meta.method-call.js > span.entity.name.function.js {
color: #d4d7d6;
}

atom-text-editor::shadow span.meta.method-call.js > span.variable.other.property.js {
color: #d4d7d6;
}

atom-text-editor::shadow span.source.js > span.variable.other.property.js {
color: #d4d7d6;
}

```

**Comment by TerrenceLJones** [comment]
@50Wliu The above worked briefly but, this is still an issue. I do not like the updates to the colors. Is there a specific way to change them in my stylesheet...as I've said before the suggestion in https://github.com/atom/one-dark-syntax/issues/60#issuecomment-172628426 did not work for me.

**Comment by MaximSokolov** [comment]
@TerrenceLJones replace `theme-one-dark-syntax` with `theme-seti-syntax`

**Comment by TerrenceLJones** [comment]
Yep @MaximSokolov before reading your comment I removed the theme specific selector and was able to get my previous color by:

@import "syntax-variables";

```css
atom-text-editor::shadow .source.js {
    .variable.other.property, .variable.other.object {
        color: @syntax-text-color;
    }

    .meta.function.body {
            .string.unquoted.js-label {
                color: @syntax-text-color;
            }
            .keyword.control.def.es {
                color: #e6cd69;
            }
    }
    .meta.function-call, .meta.method-call, .meta.function.body {
        & > .entity.name.function {
            color: @syntax-text-color;
        }
    }
}
```
Thanks for the help!
