### ISSUE TITLE
Option to color within regular expressions

### ISSUE THREAD

**Issue by brettz9** [atom/language-javascript#343]
Hi,

I think it would be quite cool to have an option to have syntax coloring applied within JavaScript regular expressions, seeing, for example, different colors for parenthetical groups, escape sequences, etc.

A while back [I implemented](http://codemirror.net/1/contrib/regex/) a pretty sophisticated regex highlighter in CodeMirror, but there are probably more generic parsers that could be used (even if they might not have all of the parsing options I added in my CM add-on). I haven't looked into Steve Levithan's, but it is probably as good or better than mine: http://stevenlevithan.com/regex/colorizer/ ([repo](https://github.com/slevithan/regex-colorizer)).

**Comment by 50Wliu** [comment]
Actually this should already be supported.  Perhaps the syntax theme you're using doesn't differentiate between the different scopes?

**Comment by brettz9** [comment]
Oh, sorry, I do see that at least Unicode escapes are colored differently, but not parenthetical groups.

Also, in the case of template literals, it doesn't color the whole embedded expression (only the `${}` characters) which I think is less helpful...

Where should I report these more specific fine-tuning requests? In looking across themes, they look pretty similar, so I'm not sure it is a theme issue.

Thanks!

**Comment by brettz9** [comment]
And is there a sample of how I can use my own stylesheet in the meantime to tweak these?

**Comment by 50Wliu** [comment]
Ok I just tested this out and it appears that everything gets a scope, so you'll need to report this to whatever theme you're using.  As for why they look pretty similar, it's probably because not many themes pay too much attention to regex-specific highlighting.

> Also, in the case of template literals, it doesn't color the whole embedded expression (only the ${} characters) which I think is less helpful...

This also seems to work fine for me - can you please paste an example here so I can check it out?

Here's an example `styles.less` file:
```less
atom-text-editor::shadow, :host
{
    .regexp
    {
        .meta.group
        {
            color: whatever;
            .punctuation.definition.group  // If you want the parentheses to have a different color than the group itself
            {
                color: whatever;
            }
        }
    }
```

To find the scopes you need to target, you can use the `editor:log-cursor-scope` command (which is bound to <kbd>Ctrl+Alt+Shift+P</kbd> on Windows, not sure about other platforms).
